#!/bin/sh

### BEGIN INIT INFO
# Provides:          myservice
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# chkconfig:         35 99 10
# Short-Description: Put a short description of the service here
# Description:       Put a long description of the service here
### END INIT INFO


DIR=/usr/local/bin
DAEMON_USER=root
DAEMON=$DIR/etcd_agent.py
DAEMON_NAME=etcd_agent

. /etc/default/etcd_agent.ini
DAEMON_OPTS="--etcd-host=${etcd_host} --etcd-path=${etcd_path} --ssl --ssl-ca=${ca} --ssl-cert=${cert} --ssl-key=${key}"
# The process ID of the script when it runs is stored here:
PIDFILE=/var/run/$DAEMON_NAME.pid

. /etc/init.d/functions

do_start () {
    echo -n "Starting etcd_agent"
    daemon --user $DAEMON_USER --pidfile $PIDFILE $DAEMON $DAEMON_OPTS
}

do_stop () {
    echo -n "Shutting down"
    killproc --pidfile
}

case "$1" in

    start|stop)
        do_${1}
        ;;

    restart|reload|force-reload)
        do_stop
        do_start
        ;;

    status)
        status_of_proc "$DAEMON_NAME" "$DAEMON" && exit 0 || exit $?
        ;;
    *)
        echo "Usage: /etc/init.d/$DAEMON_NAME {start|stop|restart|status}"
        exit 1
        ;;

esac
